// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKXN5Q1-YC930IwtQNWeGruty2FVdYInY',
    appId: '1:698578481112:web:03ff98586087d9f892ccad',
    messagingSenderId: '698578481112',
    projectId: 'modares-1957c',
    authDomain: 'modares-1957c.firebaseapp.com',
    databaseURL: 'https://modares-1957c-default-rtdb.firebaseio.com',
    storageBucket: 'modares-1957c.firebasestorage.app',
    measurementId: 'G-37HFLM7X82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJl-X4zY-XMrIe0shdzM79gqUrKbXBi1o',
    appId: '1:698578481112:android:58dc3cf7c6bb50ba92ccad',
    messagingSenderId: '698578481112',
    projectId: 'modares-1957c',
    databaseURL: 'https://modares-1957c-default-rtdb.firebaseio.com',
    storageBucket: 'modares-1957c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmXAVDMZhWtWh4Qz_HyMZAra73eAcICUM',
    appId: '1:698578481112:ios:1dca03334b7381c092ccad',
    messagingSenderId: '698578481112',
    projectId: 'modares-1957c',
    databaseURL: 'https://modares-1957c-default-rtdb.firebaseio.com',
    storageBucket: 'modares-1957c.firebasestorage.app',
    iosBundleId: 'com.example.modares',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmXAVDMZhWtWh4Qz_HyMZAra73eAcICUM',
    appId: '1:698578481112:ios:1dca03334b7381c092ccad',
    messagingSenderId: '698578481112',
    projectId: 'modares-1957c',
    databaseURL: 'https://modares-1957c-default-rtdb.firebaseio.com',
    storageBucket: 'modares-1957c.firebasestorage.app',
    iosBundleId: 'com.example.modares',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKXN5Q1-YC930IwtQNWeGruty2FVdYInY',
    appId: '1:698578481112:web:6097b7d3d8a02da292ccad',
    messagingSenderId: '698578481112',
    projectId: 'modares-1957c',
    authDomain: 'modares-1957c.firebaseapp.com',
    databaseURL: 'https://modares-1957c-default-rtdb.firebaseio.com',
    storageBucket: 'modares-1957c.firebasestorage.app',
    measurementId: 'G-CJ8NHNZD6R',
  );

}